FROM python:3.9-slim
WORKDIR /app
COPY scrapping_requirements.txt .
COPY app/pipeline.py .
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r scrapping_requirements.txt
CMD ["python", "pipeline.py"]