FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY mongo.py .
RUN mkdir -p data
ENV PYTHONPATH=/app
CMD ["python", "mongo.py", "data/unified_extracted_products.csv"]