apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: mysql
        volumeMounts:
        - name: mysql-config-volume
          mountPath: /etc/mysql/conf.d/
        - name: mysql-init-script-volume
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: mysql-config-volume
        configMap:
          name: mysql-config
      - name: mysql-init-script-volume
        configMap:
          name: mysql-init-script