apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: kubeflow
data:
  my.cnf: |-
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    skip-character-set-client-handshake
    
    [client]
    default-character-set=utf8mb4
    
    [mysql]
    default-character-set=utf8mb4
