apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: ecommerce-intelligence
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  # echo -n "mongodb://localhost:27017" | base64
  connection_string: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNw==